# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: fatindeed/mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
volumes:
  db_data:
    driver: local